<?php

namespace YasserElgammal\Green\Config;

use YasserElgammal\Green\Config\Exceptions\ConfigurationException;

final readonly class ConfigCache
{
    public function __construct(private string $path)
    {
    }

    public function path(): string
    {
        return $this->path;
    }

    public function exists(): bool
    {
        return is_file($this->path);
    }

    public function write(array $configuration, ?string $fingerprint = null): void
    {
        $directory = dirname($this->path);
        if (!is_dir($directory) && !mkdir($directory, 0755, true) && !is_dir($directory)) {
            throw new ConfigurationException("Unable to create config cache directory [{$directory}].");
        }
        $temporary = $this->path . '.' . bin2hex(random_bytes(6)) . '.tmp';
        $backup = $this->path . '.bak';
        $payload = [
            '_meta' => [
                'format' => 1,
                'generated_at' => gmdate(DATE_ATOM),
                'fingerprint' => $fingerprint,
            ],
            'config' => $configuration,
        ];
        $contents = "<?php\n\n// Generated by Green. Do not edit.\nreturn " . var_export($payload, true) . ";\n";
        if (file_put_contents($temporary, $contents, LOCK_EX) === false) {
            @unlink($temporary);
            throw new ConfigurationException("Unable to write config cache [{$this->path}].");
        }
        @chmod($temporary, 0600);

        if ($this->exists() && !rename($this->path, $backup)) {
            @unlink($temporary);
            throw new ConfigurationException("Unable to replace config cache [{$this->path}].");
        }
        if (!rename($temporary, $this->path)) {
            if (is_file($backup)) @rename($backup, $this->path);
            @unlink($temporary);
            throw new ConfigurationException("Unable to activate config cache [{$this->path}].");
        }
        if (is_file($backup)) @unlink($backup);
    }

    public function clear(): bool
    {
        return !$this->exists() || unlink($this->path);
    }

    public function isCompatible(string $fingerprint): bool
    {
        if (!$this->exists()) {
            return false;
        }

        $payload = require $this->path;

        return is_array($payload)
            && isset($payload['_meta'], $payload['config'])
            && ($payload['_meta']['format'] ?? null) === 1
            && hash_equals((string) ($payload['_meta']['fingerprint'] ?? ''), $fingerprint);
    }
}
